# -*- coding: utf-8 -*-
"""Lab5_Regression_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118FkLS78B_gRZY4o9X-otc2JNrG2AsZ2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

mydata = pd.read_csv("/content/sample_data/Boston_HousingDataSet.xls")
mydata.head()

mydata.info()

mydata.describe().T

sns.histplot(mydata['MEDV'], bins = 15, color = 'green')
plt.show()

#Step4: Data Visualisation

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(mydata['MEDV'], color = "blue")

plt.title("Median value of owner-occupied homes in $1000s")

plt.xlabel("MEDV")

plt.ylabel("Price in in $1000s")

plt.show()

#SCATTER PLOTS

sns.scatterplot(x= "AGE", y = "MEDV", data = mydata, color = "green", alpha = 0.8)

plt.title("Age of the Building vs Price")

plt.xlabel("Age of the building")

plt.ylabel("Housing Price")
plt.show()

sns.scatterplot(x= 'RM', y= 'MEDV', data= mydata, color='blue')
plt.title('RM vs MEDV')
plt.xlabel('RM')
plt.ylabel('MEDV')
plt.show()

sns.scatterplot(x= 'CRIM', y= 'MEDV', data= mydata, color='green')
plt.title('CRIM vs MEDV')
plt.xlabel('CRIM')
plt.ylabel('MEDV')
plt.show()

### Barplots Average housing prices by accessibilty of Road Highways

rad_medv_mean = mydata.groupby("RAD")["MEDV"].mean()

print(rad_medv_mean)

rad_medv_mean_df = rad_medv_mean.reset_index()
sns.barplot(x= "RAD", y= "MEDV", data= rad_medv_mean_df, color= "blue", edgecolor = "black")
plt.xlabel('RAD')
plt.ylabel('MEDV')
plt.show()

correlation_matrix = mydata.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Boston Housing Dataset')
plt.show()

