# -*- coding: utf-8 -*-
"""fun project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lND5Lp22IO8NBvKHGRe-4AtO1SnWuXBD
"""

import random

# List of choices
choices = ["rock", "paper", "scissors"]

# Get user input
user_choice = input("Enter rock, paper, or scissors: ").lower()

# Generate computer choice
computer_choice = random.choice(choices)

# Display choices
print("You chose:", user_choice)
print("Computer chose:", computer_choice)

# Check winner
if user_choice == computer_choice:
    print("It's a tie!")

elif user_choice == "rock":
    if computer_choice == "scissors":
        print("You win!")
    else:
        print("Computer wins!")

elif user_choice == "paper":
    if computer_choice == "rock":
        print("You win!")
    else:
        print("Computer wins!")

elif user_choice == "scissors":
    if computer_choice == "paper":
        print("You win!")
    else:
        print("Computer wins!")

else:
    print("Invalid input! Please enter rock, paper, or scissors.")