# -*- coding: utf-8 -*-
"""intermidiate project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16S-kRg1B4MwdQexGYrjuaci-qxAA2JV3
"""

import numpy as np
from sklearn.linear_model import LinearRegression

# Sample data (square feet vs price)
# X = input (area), y = output (price)
X = np.array([[500], [1000], [1500], [2000], [2500]])
y = np.array([100000, 200000, 300000, 400000, 500000])

# Create model
model = LinearRegression()

# Train model
model.fit(X, y)

# Take user input
area = float(input("Enter house area (in sq ft): "))

# Predict price
predicted_price = model.predict([[area]])

# Output result
print("Estimated House Price:", predicted_price[0])