# -*- coding: utf-8 -*-
"""Lab2_Control_Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syydfFMaopRiZL_MIwsurfh8wamS64D6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load CSV file
df_csv = pd.read_csv("Facebook Friends.csv")

# Load TXT file (tab separated)
df_txt = pd.read_csv("Facebook Friends.txt", sep="\t", encoding='utf-16')

# Load Excel file
df_excel = pd.read_excel("Facebook Friends.xlsx")

# Display first 5 rows
print("CSV File:")
display(df_csv.head())

print("TXT File:")
display(df_txt.head())

print("Excel File:")
display(df_excel.head())

print("CSV Info")
df_csv.info()

print("\nTXT Info")
df_txt.info()

print("\nExcel Info")
df_excel.info()

df = df_excel.copy()
df.columns

df.head()

df.tail()

df.shape

df.dtypes

df.isnull().sum()

df[df.isnull().any(axis=1)]

df['Friends'] = df['Friends'].astype(str).str.replace(",", "")
df['Friends'] = pd.to_numeric(df['Friends'])

df.dtypes

df.describe()

"""describe() gives:

count: number of values

mean : average

std : spread of data

min : smallest value

25% : first quartile

50% : median

75% : third quartile

max : largest value

The output table shows:

Columns: Variables (Age, Friends, Photos, Posts, etc.)

Rows: Statistical measures (mean, std, min, etc.)

describe() provides three main types of statistical attributes:

1️ Measures of Central Tendency

These show the center of the data:

Mean (average)

Median (50%)

2️ Measures of Spread (Dispersion)

These show how spread out the data is:

Standard Deviation (std)

Minimum

Maximum

Quartiles (25%, 75%)

Range (max - min)

3️ Distribution Information

The quartiles help identify:

Skewness

Outliers

Concentration of values

If the mean is much larger than the median, data may be right-skewed.
If max is extremely high compared to 75%, possible outliers.
"""

#histogram of age
plt.figure()
plt.hist(df['Age'], bins=10)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

#histogram of friends
plt.figure()
plt.hist(df['Friends'], bins=20)
plt.title("Friends Distribution")
plt.xlabel("Number of Friends")
plt.ylabel("Frequency")
plt.show()

#frequency plot of gender
plt.figure()
df['Gender '].value_counts().plot(kind='bar')
plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()

"""Majority of users are between 18-25 years.

Friend distribution is right-skewed.
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
os.listdir('/content/drive/MyDrive')

os.listdir('/content/drive/MyDrive/Colab Notebooks')

!jupyter nbconvert --to html FacebookAnalysis.ipynb!jupyter nbconvert --to html FacebookAnalysis.ipynb