# -*- coding: utf-8 -*-
"""advance project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hbd9ycTd8ZGNtVI-CrQ6AnNo6M1juv8D
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# Sample dataset (water parameters)
data = {
    'pH': [7, 6, 8, 5, 7.5, 6.5, 8.5, 5.5],
    'temperature': [25, 30, 20, 35, 22, 28, 18, 33],
    'turbidity': [3, 8, 2, 10, 4, 7, 1, 9],
    'pollution': [0, 1, 0, 1, 0, 1, 0, 1]  # 0 = clean, 1 = polluted
}

df = pd.DataFrame(data)

# Features and target
X = df[['pH', 'temperature', 'turbidity']]
y = df['pollution']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = DecisionTreeClassifier()

# Train
model.fit(X_train, y_train)

# User input
pH = float(input("Enter pH value: "))
temp = float(input("Enter temperature: "))
turb = float(input("Enter turbidity: "))

# Prediction
result = model.predict([[pH, temp, turb]])

# Output
if result[0] == 0:
    print("Water is Clean")
else:
    print("Water is Polluted")

