# -*- coding: utf-8 -*-
"""Lab1_Introduction_to_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ay8rfcP_TY8g9rRjwlIP0E8rTbc9glXs
"""

# Assigned values
TP = 50
FP = 8
TN = 32
FN = 10

# Total predictions
total = TP + FP + TN + FN

# calculations
accuracy = (TP + TN) / total
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1_score = (2 * precision * recall) / (precision + recall)

# results
print("Total Predictions:", total)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)

# Assigned values
SSR = 420
SSE = 180

# Total Sum of Squares
SST = SSR + SSE

# R-squared
R_squared = SSR / SST

# results
print("Total Sum of Squares (SST):", SST)
print("R-squared:", R_squared)

# Interpretation
print("Model explains more than 70% variance:", R_squared > 0.7)

# Store squared errors
e1 = 4
e2 = 9
e3 = 25
e4 = 16
e5 = 36

# Calculate MSE
MSE = (e1 + e2 + e3 + e4 + e5) / 5

# Print result
print("Mean Squared Error (MSE):", MSE)

# Assign values
ei_squared = 9
MSE = 3
p = 3
hii = 0.2
n = 25

# Cook's Distance calculation
cooks_distance = (ei_squared / (p * MSE)) * (hii / ((1 - hii) ** 2))

# Threshold
threshold = 4 / n

# Print results
print("Cook's Distance:", cooks_distance)
print("Threshold:", threshold)
print("Is observation influential:", cooks_distance > threshold)

# Assign values
a = 10      # intercept
b = 2.5       # slope
x = 12     # rainfall

# Prediction
y = a + b * x

# Print result
print("Predicted Crop Yield:", y)

