# -*- coding: utf-8 -*-
"""lab3.numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQr4WAWYVAmzwmj5Ktpp8XFo5dMPMA7w
"""

import numpy as np

w = np.array([1,2,4])

p = np.array([1,2]) #broadcasting requires atleast no. of columns to be similar

import matplotlib.pyplot as plt  #plotting graphsubplot
x= np.arange(0,10 )
y= 2*x + 3
plt.plot(x, y)

p = np.arange(0,10,2)
q= np.exp(p)
plt.plot(q,p)

"""numpy: numerical python, used for eda (exploratory data analysis) built for large array
pandas, sklearn, tenserflow requires numpy.

"""

pip install numpy

import numpy as np

a= [1, 2, 3, 4, 5]
a

arr1= np.array(a)
arr1

arr2= np.array([[1,2,3], [4,5,6]])
arr2

arr3= np.array([[[1,2,3,4],[3, 4, 77,8]], [[3,5,6,3], [3,4,5,1]]])
arr3

np.random.random((3,4)) #outer bracket is for function, inner bracket is for dimension eg: 3 cross 4 matrices

np.full((3,3,4), 10)

np.zeros((3,4))

np.eye((4)) #eye is indentity matrices

mat1= np.array([[1,2,3], [3,4,5]])
mat2= np.array([[1,2,5],[3,4,8]])
mat3= mat1+ mat2
mat3

print(mat1, mat2, mat3)

np.linspace(-90, 90,180) #180 equal intervals from -90

x2= np.random.randint(5, size= (3,4,3))
x2

import numpy as np
x = np.array((0,1,0))
y = np.array((1,0,1))
x*y

w = np.array([1,2,3])
u = np.array([4,5])
np.reshape(w,(3,1))*u

np.outer(w,u)

import matplotlib.pyplot as plt

x = np.arange(0,3*np.pi,0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
plt.plot(x,y_sin)
plt.plot(x,y_cos)
plt.xlabel('variable x')
plt.ylabel('Trigonometric function')
plt.title('Sin & Cos Function')
plt.show()

plt.subplot(2,1,1)
plt.plot(x,y_sin, color='green')
plt.title('Sine Function')
plt.xlabel('variable x')
plt.ylabel('Trigonometric function')

plt.subplot(2,1,2)
plt.plot(x,y_cos)
plt.title('Cosine Function')
plt.xlabel('variable x')
plt.ylabel('Trigonometric function')
plt.show()

p = np.arange(0,100,5)
q = p**2
d = np.exp(p)
plt.scatter(p,q)
plt.scatter(p,d/1000)

# Define y variables using the existing x array
y_linear = x
y_power = x**2
y_exp = np.exp(x)
y_log = np.log(x + 1e-9) # Add a small value to avoid log(0)

plt.figure(figsize=(10,8))

#1. Linear Function

plt.subplot(2,2,1)

plt.plot(x, y_linear, color='blue')

plt.title("Linear Function")

plt.grid()

#2. Power Function

plt.subplot(2,2,2)

plt.plot(x, y_power, color='green')

plt.title("Power Function")

plt.grid()

#3. Exponential Function

plt.subplot(2,2,3)

plt.plot(x, y_exp, color='red')

plt.title("Exponential Function")

plt.grid()

#4. Logarithmic Function

plt.subplot(2,2,4)

plt.plot(x, y_log, color='purple')

plt.title("Logarithmic Function")

plt.grid()

plt.tight_layout()

plt.show()

