# -*- coding: utf-8 -*-
"""lab4 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hbd9ycTd8ZGNtVI-CrQ6AnNo6M1juv8D
"""

!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

import numpy as pandas
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import numpy as np
a = np.array([11,22,'aa','bb',35,65])

a.dtype
print(a)

S = pd.Series(a,index = list(range(10,16)))
print(S)

It = [1,2,"aa","bb",34,45]
type(It)
listmydic = {"Snake":0,"Dog":1,"Cat":2}
myD = pd.Series(listmydic)
print(myD)

myD["Dog"]

df = pd.read_excel("/content/German-Credit_1.xls")

df.head()

df.shape

df.info()

df.columns

df.mean()

df.std()

df.describe()