# -*- coding: utf-8 -*-
"""Lab6_KNN_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5yCk6Rkxe_oiQ3-MNhhByuCKA2bAOZJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### Load the data
df_train = pd.read_csv('/content/train_KNN.csv')
df_test = pd.read_csv('/content/test_KNN.csv')

# Handle missing values
df_train = df_train.dropna(subset=['Embarked'])
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].median())
df_train = df_train.drop(['Cabin'], axis=1, errors='ignore')

df_test = df_test.dropna(subset=['Fare'])
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].median())
df_test = df_test.drop(['Cabin'], axis=1, errors='ignore')

# Drop unnecessary columns
df_train.drop(['PassengerId','Name','Ticket'], axis=1, inplace=True, errors='ignore')
df_test.drop(['PassengerId','Name','Ticket'], axis=1, inplace=True, errors='ignore')

df_train.info()

display(df_test.head())

# Convert Pclass to string for both train and test
df_train['Pclass'] = df_train['Pclass'].astype(str)
df_test['Pclass'] = df_test['Pclass'].astype(str)

# Separate target variable (Survived) from features
y_train = df_train['Survived'].astype(int)
y_test = df_test['Survived'].astype(int)

X_train = df_train.drop('Survived', axis=1)
X_test = df_test.drop('Survived', axis=1)

# Split types for features
X_train_num = X_train.select_dtypes(exclude='object')
X_train_obj = X_train.select_dtypes(include='object')

X_test_num = X_test.select_dtypes(exclude='object')
X_test_obj = X_test.select_dtypes(include='object')

# One-hot encoding for categorical features
X_train_obj = pd.get_dummies(X_train_obj, drop_first=True)
X_test_obj = pd.get_dummies(X_test_obj, drop_first=True)

# Final feature datasets by concatenating numerical and one-hot encoded categorical features
X_train = pd.concat([X_train_num, X_train_obj], axis=1)
X_test = pd.concat([X_test_num, X_test_obj], axis=1)

# Align columns - crucial for consistent feature sets
missing_cols_train = set(X_train.columns) - set(X_test.columns)
for c in missing_cols_train:
    X_test[c] = 0

missing_cols_test = set(X_test.columns) - set(X_train.columns)
for c in missing_cols_test:
    X_train[c] = 0

X_test = X_test[X_train.columns] # Ensure same column order for X_test



scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

# Ensure X_test has the same columns as X_train before transformation
X_test_aligned = X_test.reindex(columns=X_train.columns, fill_value=0)

X_test_scaled = scaler.transform(X_test_aligned)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

print("Model Comparison:")
print("KNN:", accuracy_score(y_test, y_pred_knn))
print("Logistic Regression:", accuracy_score(y_test, y_pred_lr))
print("Decision Tree:", accuracy_score(y_test, y_pred_dt))

